### PR TITLE
Update to http_ece 0.4.1 and set explicit padding size

### PR DESCRIPTION
**Pull request by martinthomson**

### CODE REVIEW

**Comment by martinthomson** [comment]
BTW, I tried running tests, but got this:

```
> node --harmony node_modules/.bin/istanbul cover _mocha -- --ui tdd test/tests/

Unable to resolve file [_mocha]
Try "istanbul help" for usage
npm ERR! Test failed.  See above for more details.
```

Probably some missing dependencies and commands.

**Comment by marco-c** [comment]
> Probably some missing dependencies and commands.

I think you need to install `mocha` globally.

**Comment by martinthomson** [comment]
> I think you need to install mocha globally.

I figured that was the case, but isn't that better put in package.json?

**Comment by marco-c** [comment]
> I figured that was the case, but isn't that better put in package.json?

Yes, I'll do that. It was a legacy from the early days where I simply run tests using the `mocha` command instead of `npm test`.

**Pull request merged**
